=begin comment

TextMagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::Sms::TextMagicClient::Object::DoEmailLookupResponse;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

TextMagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'DoEmailLookupResponse',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'address' => {
    	datatype => 'string',
    	base_name => 'address',
    	description => 'The email address passed to the call.',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => 'The email is &#x60;valid&#x60; or &#x60;invalid&#x60;.',
    	format => '',
    	read_only => '',
    		},
    'deliverability' => {
    	datatype => 'string',
    	base_name => 'deliverability',
    	description => 'The delivery status of the email address is&#x60;deliverable&#x60;, &#x60;undeliverable&#x60;. or &#x60;unknown&#x60;.',
    	format => '',
    	read_only => '',
    		},
    'reason' => {
    	datatype => 'string',
    	base_name => 'reason',
    	description => 'The reason why the checked email is invalid/undeliverable.',
    	format => '',
    	read_only => '',
    		},
    'risk' => {
    	datatype => 'string',
    	base_name => 'risk',
    	description => 'The risk score of the email is&#x60;high&#x60;, &#x60;medium&#x60;, &#x60;low&#x60; or &#x60;null&#x60;.',
    	format => '',
    	read_only => '',
    		},
    'address_type' => {
    	datatype => 'string',
    	base_name => 'addressType',
    	description => 'The email address type (domain) is &#x60;free&#x60; or &#x60;corporate&#x60;.',
    	format => '',
    	read_only => '',
    		},
    'is_disposable_address' => {
    	datatype => 'boolean',
    	base_name => 'isDisposableAddress',
    	description => 'This is &#x60;true&#x60; if the domain is in the list of disposable email addresses; otherwise, it returns as &#x60;false&#x60;.',
    	format => '',
    	read_only => '',
    		},
    'suggestion' => {
    	datatype => 'string',
    	base_name => 'suggestion',
    	description => 'Null if nothing is suggested; however, if there is a potential typo in the email address, the closest suggestion is provided.',
    	format => '',
    	read_only => '',
    		},
    'email_role' => {
    	datatype => 'string',
    	base_name => 'emailRole',
    	description => 'Checks the mailbox part of the email to see whether it matches a specific role type (‘admin’, ‘sales’, ‘webmaster’).',
    	format => '',
    	read_only => '',
    		},
    'local_part' => {
    	datatype => 'string',
    	base_name => 'localPart',
    	description => 'The local part of the email address.',
    	format => '',
    	read_only => '',
    		},
    'domain_part' => {
    	datatype => 'string',
    	base_name => 'domainPart',
    	description => 'The domain part of the email address.',
    	format => '',
    	read_only => '',
    		},
    'exchange' => {
    	datatype => 'string',
    	base_name => 'exchange',
    	description => 'Email exchange server domain name (MX record value).',
    	format => '',
    	read_only => '',
    		},
    'preference' => {
    	datatype => 'int',
    	base_name => 'preference',
    	description => 'MX record preference.',
    	format => '',
    	read_only => '',
    		},
    'is_in_white_list' => {
    	datatype => 'boolean',
    	base_name => 'isInWhiteList',
    	description => '&#x60;true&#x60; if the email address exists in the TextMagic whitelist. ',
    	format => '',
    	read_only => '',
    		},
    'is_in_black_list' => {
    	datatype => 'boolean',
    	base_name => 'isInBlackList',
    	description => '&#x60;true&#x60; if the email address exists in the TextMagic blacklist. ',
    	format => '',
    	read_only => '',
    		},
    'has_mx' => {
    	datatype => 'boolean',
    	base_name => 'hasMx',
    	description => '&#x60;true&#x60; if the email address domain has an MX record. ',
    	format => '',
    	read_only => '',
    		},
    'has_aa' => {
    	datatype => 'boolean',
    	base_name => 'hasAa',
    	description => '&#x60;true&#x60; if the email address domain has an A record (IPv4). ',
    	format => '',
    	read_only => '',
    		},
    'has_aaaa' => {
    	datatype => 'boolean',
    	base_name => 'hasAaaa',
    	description => '&#x60;true&#x60; if the email address domain has an AAAA record (IPv6). ',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'address' => 'string',
    'status' => 'string',
    'deliverability' => 'string',
    'reason' => 'string',
    'risk' => 'string',
    'address_type' => 'string',
    'is_disposable_address' => 'boolean',
    'suggestion' => 'string',
    'email_role' => 'string',
    'local_part' => 'string',
    'domain_part' => 'string',
    'exchange' => 'string',
    'preference' => 'int',
    'is_in_white_list' => 'boolean',
    'is_in_black_list' => 'boolean',
    'has_mx' => 'boolean',
    'has_aa' => 'boolean',
    'has_aaaa' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'address' => 'address',
    'status' => 'status',
    'deliverability' => 'deliverability',
    'reason' => 'reason',
    'risk' => 'risk',
    'address_type' => 'addressType',
    'is_disposable_address' => 'isDisposableAddress',
    'suggestion' => 'suggestion',
    'email_role' => 'emailRole',
    'local_part' => 'localPart',
    'domain_part' => 'domainPart',
    'exchange' => 'exchange',
    'preference' => 'preference',
    'is_in_white_list' => 'isInWhiteList',
    'is_in_black_list' => 'isInBlackList',
    'has_mx' => 'hasMx',
    'has_aa' => 'hasAa',
    'has_aaaa' => 'hasAaaa'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
