=begin comment

TextMagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::Sms::TextMagicClient::Object::GetContactsAutocompleteResponseItem;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

TextMagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'GetContactsAutocompleteResponseItem',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'entity_id' => {
    	datatype => 'int',
    	base_name => 'entityId',
    	description => 'Id of entity. 0 if object is a reply.',
    	format => '',
    	read_only => '',
    		},
    'entity_type' => {
    	datatype => 'string',
    	base_name => 'entityType',
    	description => 'Entry type: * **contact** if it is related to a contact; * **list** if it is related to a contact list; * **reply** if it is related to an incoming message. ',
    	format => '',
    	read_only => '',
    		},
    'value' => {
    	datatype => 'string',
    	base_name => 'value',
    	description => 'ID of the contact/list if entityType is contact/list OR phone number if entityType is reply.',
    	format => '',
    	read_only => '',
    		},
    'label' => {
    	datatype => 'string',
    	base_name => 'label',
    	description => 'Name of the contact/list if entityType is contact/list OR phone number if entityType is reply.',
    	format => '',
    	read_only => '',
    		},
    'shared_by' => {
    	datatype => 'string',
    	base_name => 'sharedBy',
    	description => 'If contact or list was shared by another sub-account, the name of this user will be shown.',
    	format => '',
    	read_only => '',
    		},
    'is_shared' => {
    	datatype => 'boolean',
    	base_name => 'isShared',
    	description => 'If contact or list was shared by another sub-account then &#x60;true&#x60; will be set.',
    	format => '',
    	read_only => '',
    		},
    'avatar' => {
    	datatype => 'string',
    	base_name => 'avatar',
    	description => 'Contact avatar URI.',
    	format => '',
    	read_only => '',
    		},
    'favorited' => {
    	datatype => 'boolean',
    	base_name => 'favorited',
    	description => 'If contact has been marked as favorite.',
    	format => '',
    	read_only => '',
    		},
    'user_id' => {
    	datatype => 'int',
    	base_name => 'userId',
    	description => 'Owner ID of the contact/list (if it was shared).',
    	format => '',
    	read_only => '',
    		},
    'country_name' => {
    	datatype => 'string',
    	base_name => 'countryName',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'qposition' => {
    	datatype => 'int',
    	base_name => 'qposition',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'rposition' => {
    	datatype => 'int',
    	base_name => 'rposition',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'entity_id' => 'int',
    'entity_type' => 'string',
    'value' => 'string',
    'label' => 'string',
    'shared_by' => 'string',
    'is_shared' => 'boolean',
    'avatar' => 'string',
    'favorited' => 'boolean',
    'user_id' => 'int',
    'country_name' => 'string',
    'qposition' => 'int',
    'rposition' => 'int'
} );

__PACKAGE__->attribute_map( {
    'entity_id' => 'entityId',
    'entity_type' => 'entityType',
    'value' => 'value',
    'label' => 'label',
    'shared_by' => 'sharedBy',
    'is_shared' => 'isShared',
    'avatar' => 'avatar',
    'favorited' => 'favorited',
    'user_id' => 'userId',
    'country_name' => 'countryName',
    'qposition' => 'qposition',
    'rposition' => 'rposition'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
