curl "https://api.github.com/orgs/textmagic/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone

git clone https://github.com/textmagic/textmagic-sms-api-python.git
git clone https://github.com/textmagic/textmagic-sms-api-php.git
git clone https://github.com/textmagic/textmagic-c-sharp-wrapper-class-library.git
git clone https://github.com/textmagic/textmagic-sms-api-java.git
git clone https://github.com/textmagic/CodeIgniter-TextMagic-API.git
git clone https://github.com/textmagic/textmagic-rest-nodejs.git
git clone https://github.com/textmagic/textmagic-rest-go.git
git clone https://github.com/textmagic/textmagic-rest-python.git
git clone https://github.com/textmagic/textmagic-rest-bash.git
git clone https://github.com/textmagic/textmagic-rest-csharp.git
git clone https://github.com/textmagic/textmagic-rest-java.git
git clone https://github.com/textmagic/textmagic-rest-object-pascal.git
git clone https://github.com/textmagic/textmagic-rest-perl.git
git clone https://github.com/textmagic/textmagic-rest-php.git
git clone https://github.com/textmagic/textmagic-rest-vbnet.git
git clone https://github.com/textmagic/textmagic-rest-ruby.git
git clone https://github.com/textmagic/textmagic-rest-cpp.git
git clone https://github.com/textmagic/assetic-bundle.git
git clone https://github.com/textmagic/SIP.js.git
git clone https://github.com/textmagic/phpari.git
git clone https://github.com/textmagic/fullcalendar-vue.git
git clone https://github.com/textmagic/textmagic-rest-php-v2.git
git clone https://github.com/textmagic/textmagic-rest-nodejs-v2.git
git clone https://github.com/textmagic/textmagic-rest-java-v2.git
git clone https://github.com/textmagic/textmagic-rest-go-v2.git
git clone https://github.com/textmagic/textmagic-rest-python-v2.git
git clone https://github.com/textmagic/textmagic-rest-ruby-v2.git
git clone https://github.com/textmagic/textmagic-rest-cpp-v2.git
git clone https://github.com/textmagic/textmagic-rest-perl-v2.git
git clone https://github.com/textmagic/textmagic-rest-csharp-v2.git
git clone https://github.com/textmagic/redoc.git
git clone https://github.com/textmagic/vue-dropdown-menu.git
