/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.PingResponse = factory(root.TextmagicClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PingResponse model module.
   * @module model/PingResponse
   * @version 2.0.1588
   */

  /**
   * Constructs a new <code>PingResponse</code>.
   * @alias module:model/PingResponse
   * @class
   * @param userId {Number} Current user Id.
   * @param ping {String} Pong.
   * @param utcDateTime {String} Current date and time.
   */
  var exports = function(userId, ping, utcDateTime) {
    this.userId = userId;
    this.ping = ping;
    this.utcDateTime = utcDateTime;
  };

  /**
   * Constructs a <code>PingResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PingResponse} obj Optional instance to populate.
   * @return {module:model/PingResponse} The populated <code>PingResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('ping'))
        obj.ping = ApiClient.convertToType(data['ping'], 'String');
      if (data.hasOwnProperty('utcDateTime'))
        obj.utcDateTime = ApiClient.convertToType(data['utcDateTime'], 'String');
    }
    return obj;
  }

  /**
   * Current user Id.
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  /**
   * Pong.
   * @member {String} ping
   */
  exports.prototype.ping = undefined;

  /**
   * Current date and time.
   * @member {String} utcDateTime
   */
  exports.prototype.utcDateTime = undefined;

  return exports;

}));
