/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.SenderSettingsItem = factory(root.TextmagicClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SenderSettingsItem model module.
   * @module model/SenderSettingsItem
   * @version 2.0.1588
   */

  /**
   * Constructs a new <code>SenderSettingsItem</code>.
   * @alias module:model/SenderSettingsItem
   * @class
   * @param country {String} The 2-letter ISO country code of the recipient's phone number. 
   * @param phone {String} Phone enabled for sending to a specified country.
   */
  var exports = function(country, phone) {
    this.country = country;
    this.phone = phone;
  };

  /**
   * Constructs a <code>SenderSettingsItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SenderSettingsItem} obj Optional instance to populate.
   * @return {module:model/SenderSettingsItem} The populated <code>SenderSettingsItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
    }
    return obj;
  }

  /**
   * The 2-letter ISO country code of the recipient's phone number. 
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * Phone enabled for sending to a specified country.
   * @member {String} phone
   */
  exports.prototype.phone = undefined;

  return exports;

}));
