/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GetMessagePriceResponseCountriesItem
 */

public class GetMessagePriceResponseCountriesItem {
  @SerializedName("country")
  private String country = null;

  @SerializedName("countryName")
  private String countryName = null;

  @SerializedName("allowDedicated")
  private Boolean allowDedicated = null;

  @SerializedName("count")
  private BigDecimal count = null;

  @SerializedName("max")
  private BigDecimal max = null;

  @SerializedName("sum")
  private String sum = null;

  @SerializedName("landline")
  private BigDecimal landline = null;

  public GetMessagePriceResponseCountriesItem country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The 2-letter ISO country code.
   * @return country
  **/
  @ApiModelProperty(example = "US", required = true, value = "The 2-letter ISO country code.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public GetMessagePriceResponseCountriesItem countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * Country name.
   * @return countryName
  **/
  @ApiModelProperty(example = "United State", required = true, value = "Country name.")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public GetMessagePriceResponseCountriesItem allowDedicated(Boolean allowDedicated) {
    this.allowDedicated = allowDedicated;
    return this;
  }

   /**
   * Is allowed to use a dedicated number?
   * @return allowDedicated
  **/
  @ApiModelProperty(example = "true", required = true, value = "Is allowed to use a dedicated number?")
  public Boolean isAllowDedicated() {
    return allowDedicated;
  }

  public void setAllowDedicated(Boolean allowDedicated) {
    this.allowDedicated = allowDedicated;
  }

  public GetMessagePriceResponseCountriesItem count(BigDecimal count) {
    this.count = count;
    return this;
  }

   /**
   * Parts count to send.
   * @return count
  **/
  @ApiModelProperty(example = "1.0", required = true, value = "Parts count to send.")
  public BigDecimal getCount() {
    return count;
  }

  public void setCount(BigDecimal count) {
    this.count = count;
  }

  public GetMessagePriceResponseCountriesItem max(BigDecimal max) {
    this.max = max;
    return this;
  }

   /**
   * Maximum parts to send.
   * @return max
  **/
  @ApiModelProperty(example = "6.0", required = true, value = "Maximum parts to send.")
  public BigDecimal getMax() {
    return max;
  }

  public void setMax(BigDecimal max) {
    this.max = max;
  }

  public GetMessagePriceResponseCountriesItem sum(String sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Total price to send.
   * @return sum
  **/
  @ApiModelProperty(example = "1", required = true, value = "Total price to send.")
  public String getSum() {
    return sum;
  }

  public void setSum(String sum) {
    this.sum = sum;
  }

  public GetMessagePriceResponseCountriesItem landline(BigDecimal landline) {
    this.landline = landline;
    return this;
  }

   /**
   * Is this a landline number?
   * @return landline
  **/
  @ApiModelProperty(example = "0.0", required = true, value = "Is this a landline number?")
  public BigDecimal getLandline() {
    return landline;
  }

  public void setLandline(BigDecimal landline) {
    this.landline = landline;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMessagePriceResponseCountriesItem getMessagePriceResponseCountriesItem = (GetMessagePriceResponseCountriesItem) o;
    return Objects.equals(this.country, getMessagePriceResponseCountriesItem.country) &&
        Objects.equals(this.countryName, getMessagePriceResponseCountriesItem.countryName) &&
        Objects.equals(this.allowDedicated, getMessagePriceResponseCountriesItem.allowDedicated) &&
        Objects.equals(this.count, getMessagePriceResponseCountriesItem.count) &&
        Objects.equals(this.max, getMessagePriceResponseCountriesItem.max) &&
        Objects.equals(this.sum, getMessagePriceResponseCountriesItem.sum) &&
        Objects.equals(this.landline, getMessagePriceResponseCountriesItem.landline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, countryName, allowDedicated, count, max, sum, landline);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMessagePriceResponseCountriesItem {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    allowDedicated: ").append(toIndentedString(allowDedicated)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    landline: ").append(toIndentedString(landline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

