/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.MessageOut;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetOutboundMessagesHistoryPaginatedResponse
 */

public class GetOutboundMessagesHistoryPaginatedResponse {
  @SerializedName("lastId")
  private Integer lastId = null;

  @SerializedName("nextLastId")
  private Integer nextLastId = null;

  @SerializedName("limit")
  private Integer limit = null;

  @SerializedName("resources")
  private List<MessageOut> resources = new ArrayList<MessageOut>();

  public GetOutboundMessagesHistoryPaginatedResponse lastId(Integer lastId) {
    this.lastId = lastId;
    return this;
  }

   /**
   * Get lastId
   * @return lastId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getLastId() {
    return lastId;
  }

  public void setLastId(Integer lastId) {
    this.lastId = lastId;
  }

  public GetOutboundMessagesHistoryPaginatedResponse nextLastId(Integer nextLastId) {
    this.nextLastId = nextLastId;
    return this;
  }

   /**
   * Get nextLastId
   * @return nextLastId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getNextLastId() {
    return nextLastId;
  }

  public void setNextLastId(Integer nextLastId) {
    this.nextLastId = nextLastId;
  }

  public GetOutboundMessagesHistoryPaginatedResponse limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * The number of results per page.
   * @return limit
  **/
  @ApiModelProperty(example = "10", required = true, value = "The number of results per page.")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public GetOutboundMessagesHistoryPaginatedResponse resources(List<MessageOut> resources) {
    this.resources = resources;
    return this;
  }

  public GetOutboundMessagesHistoryPaginatedResponse addResourcesItem(MessageOut resourcesItem) {
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MessageOut> getResources() {
    return resources;
  }

  public void setResources(List<MessageOut> resources) {
    this.resources = resources;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOutboundMessagesHistoryPaginatedResponse getOutboundMessagesHistoryPaginatedResponse = (GetOutboundMessagesHistoryPaginatedResponse) o;
    return Objects.equals(this.lastId, getOutboundMessagesHistoryPaginatedResponse.lastId) &&
        Objects.equals(this.nextLastId, getOutboundMessagesHistoryPaginatedResponse.nextLastId) &&
        Objects.equals(this.limit, getOutboundMessagesHistoryPaginatedResponse.limit) &&
        Objects.equals(this.resources, getOutboundMessagesHistoryPaginatedResponse.resources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastId, nextLastId, limit, resources);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOutboundMessagesHistoryPaginatedResponse {\n");
    
    sb.append("    lastId: ").append(toIndentedString(lastId)).append("\n");
    sb.append("    nextLastId: ").append(toIndentedString(nextLastId)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

