/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetStateResponse
 */

public class GetStateResponse {
  @SerializedName("systemCacheClear")
  private Integer systemCacheClear = null;

  @SerializedName("systemExit")
  private Integer systemExit = null;

  @SerializedName("systemAlert")
  private Integer systemAlert = null;

  @SerializedName("systemAccountStateChanged")
  private Integer systemAccountStateChanged = null;

  @SerializedName("messageDeleted")
  private Integer messageDeleted = null;

  @SerializedName("messageIncoming")
  private Integer messageIncoming = null;

  @SerializedName("messageIncomingDeleted")
  private Integer messageIncomingDeleted = null;

  @SerializedName("messageStateChanged")
  private Integer messageStateChanged = null;

  @SerializedName("messageBulkEnd")
  private Integer messageBulkEnd = null;

  @SerializedName("messageWipeEnd")
  private Integer messageWipeEnd = null;

  @SerializedName("messageSent")
  private Integer messageSent = null;

  @SerializedName("messageSessionDeleted")
  private Integer messageSessionDeleted = null;

  @SerializedName("messageCacheClear")
  private Integer messageCacheClear = null;

  @SerializedName("messageIncomingCacheClear")
  private Integer messageIncomingCacheClear = null;

  @SerializedName("messageScheduleAdded")
  private Integer messageScheduleAdded = null;

  @SerializedName("messageScheduleStateChanged")
  private Integer messageScheduleStateChanged = null;

  @SerializedName("messageScheduleDeleted")
  private Integer messageScheduleDeleted = null;

  @SerializedName("messageScheduleCacheClear")
  private Integer messageScheduleCacheClear = null;

  @SerializedName("messageTemplateCacheClear")
  private Integer messageTemplateCacheClear = null;

  @SerializedName("callFinished")
  private Integer callFinished = null;

  @SerializedName("chatCreated")
  private Integer chatCreated = null;

  @SerializedName("chatMarkedAsRead")
  private Integer chatMarkedAsRead = null;

  @SerializedName("chatMuted")
  private Integer chatMuted = null;

  @SerializedName("chatUnmuted")
  private Integer chatUnmuted = null;

  @SerializedName("chatPinned")
  private Integer chatPinned = null;

  @SerializedName("chatUnpinned")
  private Integer chatUnpinned = null;

  @SerializedName("chatDeleted")
  private Integer chatDeleted = null;

  @SerializedName("chatClosed")
  private Integer chatClosed = null;

  @SerializedName("chatReopened")
  private Integer chatReopened = null;

  @SerializedName("chatCacheClear")
  private Integer chatCacheClear = null;

  @SerializedName("contactAdded")
  private Integer contactAdded = null;

  @SerializedName("contactDeleted")
  private Integer contactDeleted = null;

  @SerializedName("contactStateChanged")
  private Integer contactStateChanged = null;

  @SerializedName("listAdded")
  private Integer listAdded = null;

  @SerializedName("listDeleted")
  private Integer listDeleted = null;

  @SerializedName("listStateChanged")
  private Integer listStateChanged = null;

  @SerializedName("contactWipeEnd")
  private Integer contactWipeEnd = null;

  @SerializedName("contactImportEnd")
  private Integer contactImportEnd = null;

  @SerializedName("contactCacheClear")
  private Integer contactCacheClear = null;

  @SerializedName("listCacheClear")
  private Integer listCacheClear = null;

  @SerializedName("customFieldsCacheClear")
  private Integer customFieldsCacheClear = null;

  public GetStateResponse systemCacheClear(Integer systemCacheClear) {
    this.systemCacheClear = systemCacheClear;
    return this;
  }

   /**
   * Get systemCacheClear
   * @return systemCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getSystemCacheClear() {
    return systemCacheClear;
  }

  public void setSystemCacheClear(Integer systemCacheClear) {
    this.systemCacheClear = systemCacheClear;
  }

  public GetStateResponse systemExit(Integer systemExit) {
    this.systemExit = systemExit;
    return this;
  }

   /**
   * Get systemExit
   * @return systemExit
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getSystemExit() {
    return systemExit;
  }

  public void setSystemExit(Integer systemExit) {
    this.systemExit = systemExit;
  }

  public GetStateResponse systemAlert(Integer systemAlert) {
    this.systemAlert = systemAlert;
    return this;
  }

   /**
   * Get systemAlert
   * @return systemAlert
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getSystemAlert() {
    return systemAlert;
  }

  public void setSystemAlert(Integer systemAlert) {
    this.systemAlert = systemAlert;
  }

  public GetStateResponse systemAccountStateChanged(Integer systemAccountStateChanged) {
    this.systemAccountStateChanged = systemAccountStateChanged;
    return this;
  }

   /**
   * Get systemAccountStateChanged
   * @return systemAccountStateChanged
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getSystemAccountStateChanged() {
    return systemAccountStateChanged;
  }

  public void setSystemAccountStateChanged(Integer systemAccountStateChanged) {
    this.systemAccountStateChanged = systemAccountStateChanged;
  }

  public GetStateResponse messageDeleted(Integer messageDeleted) {
    this.messageDeleted = messageDeleted;
    return this;
  }

   /**
   * Get messageDeleted
   * @return messageDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageDeleted() {
    return messageDeleted;
  }

  public void setMessageDeleted(Integer messageDeleted) {
    this.messageDeleted = messageDeleted;
  }

  public GetStateResponse messageIncoming(Integer messageIncoming) {
    this.messageIncoming = messageIncoming;
    return this;
  }

   /**
   * Get messageIncoming
   * @return messageIncoming
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageIncoming() {
    return messageIncoming;
  }

  public void setMessageIncoming(Integer messageIncoming) {
    this.messageIncoming = messageIncoming;
  }

  public GetStateResponse messageIncomingDeleted(Integer messageIncomingDeleted) {
    this.messageIncomingDeleted = messageIncomingDeleted;
    return this;
  }

   /**
   * Get messageIncomingDeleted
   * @return messageIncomingDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageIncomingDeleted() {
    return messageIncomingDeleted;
  }

  public void setMessageIncomingDeleted(Integer messageIncomingDeleted) {
    this.messageIncomingDeleted = messageIncomingDeleted;
  }

  public GetStateResponse messageStateChanged(Integer messageStateChanged) {
    this.messageStateChanged = messageStateChanged;
    return this;
  }

   /**
   * Get messageStateChanged
   * @return messageStateChanged
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageStateChanged() {
    return messageStateChanged;
  }

  public void setMessageStateChanged(Integer messageStateChanged) {
    this.messageStateChanged = messageStateChanged;
  }

  public GetStateResponse messageBulkEnd(Integer messageBulkEnd) {
    this.messageBulkEnd = messageBulkEnd;
    return this;
  }

   /**
   * Get messageBulkEnd
   * @return messageBulkEnd
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageBulkEnd() {
    return messageBulkEnd;
  }

  public void setMessageBulkEnd(Integer messageBulkEnd) {
    this.messageBulkEnd = messageBulkEnd;
  }

  public GetStateResponse messageWipeEnd(Integer messageWipeEnd) {
    this.messageWipeEnd = messageWipeEnd;
    return this;
  }

   /**
   * Get messageWipeEnd
   * @return messageWipeEnd
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageWipeEnd() {
    return messageWipeEnd;
  }

  public void setMessageWipeEnd(Integer messageWipeEnd) {
    this.messageWipeEnd = messageWipeEnd;
  }

  public GetStateResponse messageSent(Integer messageSent) {
    this.messageSent = messageSent;
    return this;
  }

   /**
   * Get messageSent
   * @return messageSent
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageSent() {
    return messageSent;
  }

  public void setMessageSent(Integer messageSent) {
    this.messageSent = messageSent;
  }

  public GetStateResponse messageSessionDeleted(Integer messageSessionDeleted) {
    this.messageSessionDeleted = messageSessionDeleted;
    return this;
  }

   /**
   * Get messageSessionDeleted
   * @return messageSessionDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageSessionDeleted() {
    return messageSessionDeleted;
  }

  public void setMessageSessionDeleted(Integer messageSessionDeleted) {
    this.messageSessionDeleted = messageSessionDeleted;
  }

  public GetStateResponse messageCacheClear(Integer messageCacheClear) {
    this.messageCacheClear = messageCacheClear;
    return this;
  }

   /**
   * Get messageCacheClear
   * @return messageCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageCacheClear() {
    return messageCacheClear;
  }

  public void setMessageCacheClear(Integer messageCacheClear) {
    this.messageCacheClear = messageCacheClear;
  }

  public GetStateResponse messageIncomingCacheClear(Integer messageIncomingCacheClear) {
    this.messageIncomingCacheClear = messageIncomingCacheClear;
    return this;
  }

   /**
   * Get messageIncomingCacheClear
   * @return messageIncomingCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageIncomingCacheClear() {
    return messageIncomingCacheClear;
  }

  public void setMessageIncomingCacheClear(Integer messageIncomingCacheClear) {
    this.messageIncomingCacheClear = messageIncomingCacheClear;
  }

  public GetStateResponse messageScheduleAdded(Integer messageScheduleAdded) {
    this.messageScheduleAdded = messageScheduleAdded;
    return this;
  }

   /**
   * Get messageScheduleAdded
   * @return messageScheduleAdded
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageScheduleAdded() {
    return messageScheduleAdded;
  }

  public void setMessageScheduleAdded(Integer messageScheduleAdded) {
    this.messageScheduleAdded = messageScheduleAdded;
  }

  public GetStateResponse messageScheduleStateChanged(Integer messageScheduleStateChanged) {
    this.messageScheduleStateChanged = messageScheduleStateChanged;
    return this;
  }

   /**
   * Get messageScheduleStateChanged
   * @return messageScheduleStateChanged
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageScheduleStateChanged() {
    return messageScheduleStateChanged;
  }

  public void setMessageScheduleStateChanged(Integer messageScheduleStateChanged) {
    this.messageScheduleStateChanged = messageScheduleStateChanged;
  }

  public GetStateResponse messageScheduleDeleted(Integer messageScheduleDeleted) {
    this.messageScheduleDeleted = messageScheduleDeleted;
    return this;
  }

   /**
   * Get messageScheduleDeleted
   * @return messageScheduleDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageScheduleDeleted() {
    return messageScheduleDeleted;
  }

  public void setMessageScheduleDeleted(Integer messageScheduleDeleted) {
    this.messageScheduleDeleted = messageScheduleDeleted;
  }

  public GetStateResponse messageScheduleCacheClear(Integer messageScheduleCacheClear) {
    this.messageScheduleCacheClear = messageScheduleCacheClear;
    return this;
  }

   /**
   * Get messageScheduleCacheClear
   * @return messageScheduleCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageScheduleCacheClear() {
    return messageScheduleCacheClear;
  }

  public void setMessageScheduleCacheClear(Integer messageScheduleCacheClear) {
    this.messageScheduleCacheClear = messageScheduleCacheClear;
  }

  public GetStateResponse messageTemplateCacheClear(Integer messageTemplateCacheClear) {
    this.messageTemplateCacheClear = messageTemplateCacheClear;
    return this;
  }

   /**
   * Get messageTemplateCacheClear
   * @return messageTemplateCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getMessageTemplateCacheClear() {
    return messageTemplateCacheClear;
  }

  public void setMessageTemplateCacheClear(Integer messageTemplateCacheClear) {
    this.messageTemplateCacheClear = messageTemplateCacheClear;
  }

  public GetStateResponse callFinished(Integer callFinished) {
    this.callFinished = callFinished;
    return this;
  }

   /**
   * Get callFinished
   * @return callFinished
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getCallFinished() {
    return callFinished;
  }

  public void setCallFinished(Integer callFinished) {
    this.callFinished = callFinished;
  }

  public GetStateResponse chatCreated(Integer chatCreated) {
    this.chatCreated = chatCreated;
    return this;
  }

   /**
   * Get chatCreated
   * @return chatCreated
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatCreated() {
    return chatCreated;
  }

  public void setChatCreated(Integer chatCreated) {
    this.chatCreated = chatCreated;
  }

  public GetStateResponse chatMarkedAsRead(Integer chatMarkedAsRead) {
    this.chatMarkedAsRead = chatMarkedAsRead;
    return this;
  }

   /**
   * Get chatMarkedAsRead
   * @return chatMarkedAsRead
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatMarkedAsRead() {
    return chatMarkedAsRead;
  }

  public void setChatMarkedAsRead(Integer chatMarkedAsRead) {
    this.chatMarkedAsRead = chatMarkedAsRead;
  }

  public GetStateResponse chatMuted(Integer chatMuted) {
    this.chatMuted = chatMuted;
    return this;
  }

   /**
   * Get chatMuted
   * @return chatMuted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatMuted() {
    return chatMuted;
  }

  public void setChatMuted(Integer chatMuted) {
    this.chatMuted = chatMuted;
  }

  public GetStateResponse chatUnmuted(Integer chatUnmuted) {
    this.chatUnmuted = chatUnmuted;
    return this;
  }

   /**
   * Get chatUnmuted
   * @return chatUnmuted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatUnmuted() {
    return chatUnmuted;
  }

  public void setChatUnmuted(Integer chatUnmuted) {
    this.chatUnmuted = chatUnmuted;
  }

  public GetStateResponse chatPinned(Integer chatPinned) {
    this.chatPinned = chatPinned;
    return this;
  }

   /**
   * Get chatPinned
   * @return chatPinned
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatPinned() {
    return chatPinned;
  }

  public void setChatPinned(Integer chatPinned) {
    this.chatPinned = chatPinned;
  }

  public GetStateResponse chatUnpinned(Integer chatUnpinned) {
    this.chatUnpinned = chatUnpinned;
    return this;
  }

   /**
   * Get chatUnpinned
   * @return chatUnpinned
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatUnpinned() {
    return chatUnpinned;
  }

  public void setChatUnpinned(Integer chatUnpinned) {
    this.chatUnpinned = chatUnpinned;
  }

  public GetStateResponse chatDeleted(Integer chatDeleted) {
    this.chatDeleted = chatDeleted;
    return this;
  }

   /**
   * Get chatDeleted
   * @return chatDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatDeleted() {
    return chatDeleted;
  }

  public void setChatDeleted(Integer chatDeleted) {
    this.chatDeleted = chatDeleted;
  }

  public GetStateResponse chatClosed(Integer chatClosed) {
    this.chatClosed = chatClosed;
    return this;
  }

   /**
   * Get chatClosed
   * @return chatClosed
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatClosed() {
    return chatClosed;
  }

  public void setChatClosed(Integer chatClosed) {
    this.chatClosed = chatClosed;
  }

  public GetStateResponse chatReopened(Integer chatReopened) {
    this.chatReopened = chatReopened;
    return this;
  }

   /**
   * Get chatReopened
   * @return chatReopened
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatReopened() {
    return chatReopened;
  }

  public void setChatReopened(Integer chatReopened) {
    this.chatReopened = chatReopened;
  }

  public GetStateResponse chatCacheClear(Integer chatCacheClear) {
    this.chatCacheClear = chatCacheClear;
    return this;
  }

   /**
   * Get chatCacheClear
   * @return chatCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChatCacheClear() {
    return chatCacheClear;
  }

  public void setChatCacheClear(Integer chatCacheClear) {
    this.chatCacheClear = chatCacheClear;
  }

  public GetStateResponse contactAdded(Integer contactAdded) {
    this.contactAdded = contactAdded;
    return this;
  }

   /**
   * Get contactAdded
   * @return contactAdded
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getContactAdded() {
    return contactAdded;
  }

  public void setContactAdded(Integer contactAdded) {
    this.contactAdded = contactAdded;
  }

  public GetStateResponse contactDeleted(Integer contactDeleted) {
    this.contactDeleted = contactDeleted;
    return this;
  }

   /**
   * Get contactDeleted
   * @return contactDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getContactDeleted() {
    return contactDeleted;
  }

  public void setContactDeleted(Integer contactDeleted) {
    this.contactDeleted = contactDeleted;
  }

  public GetStateResponse contactStateChanged(Integer contactStateChanged) {
    this.contactStateChanged = contactStateChanged;
    return this;
  }

   /**
   * Get contactStateChanged
   * @return contactStateChanged
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getContactStateChanged() {
    return contactStateChanged;
  }

  public void setContactStateChanged(Integer contactStateChanged) {
    this.contactStateChanged = contactStateChanged;
  }

  public GetStateResponse listAdded(Integer listAdded) {
    this.listAdded = listAdded;
    return this;
  }

   /**
   * Get listAdded
   * @return listAdded
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getListAdded() {
    return listAdded;
  }

  public void setListAdded(Integer listAdded) {
    this.listAdded = listAdded;
  }

  public GetStateResponse listDeleted(Integer listDeleted) {
    this.listDeleted = listDeleted;
    return this;
  }

   /**
   * Get listDeleted
   * @return listDeleted
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getListDeleted() {
    return listDeleted;
  }

  public void setListDeleted(Integer listDeleted) {
    this.listDeleted = listDeleted;
  }

  public GetStateResponse listStateChanged(Integer listStateChanged) {
    this.listStateChanged = listStateChanged;
    return this;
  }

   /**
   * Get listStateChanged
   * @return listStateChanged
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getListStateChanged() {
    return listStateChanged;
  }

  public void setListStateChanged(Integer listStateChanged) {
    this.listStateChanged = listStateChanged;
  }

  public GetStateResponse contactWipeEnd(Integer contactWipeEnd) {
    this.contactWipeEnd = contactWipeEnd;
    return this;
  }

   /**
   * Get contactWipeEnd
   * @return contactWipeEnd
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getContactWipeEnd() {
    return contactWipeEnd;
  }

  public void setContactWipeEnd(Integer contactWipeEnd) {
    this.contactWipeEnd = contactWipeEnd;
  }

  public GetStateResponse contactImportEnd(Integer contactImportEnd) {
    this.contactImportEnd = contactImportEnd;
    return this;
  }

   /**
   * Get contactImportEnd
   * @return contactImportEnd
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getContactImportEnd() {
    return contactImportEnd;
  }

  public void setContactImportEnd(Integer contactImportEnd) {
    this.contactImportEnd = contactImportEnd;
  }

  public GetStateResponse contactCacheClear(Integer contactCacheClear) {
    this.contactCacheClear = contactCacheClear;
    return this;
  }

   /**
   * Get contactCacheClear
   * @return contactCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getContactCacheClear() {
    return contactCacheClear;
  }

  public void setContactCacheClear(Integer contactCacheClear) {
    this.contactCacheClear = contactCacheClear;
  }

  public GetStateResponse listCacheClear(Integer listCacheClear) {
    this.listCacheClear = listCacheClear;
    return this;
  }

   /**
   * Get listCacheClear
   * @return listCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getListCacheClear() {
    return listCacheClear;
  }

  public void setListCacheClear(Integer listCacheClear) {
    this.listCacheClear = listCacheClear;
  }

  public GetStateResponse customFieldsCacheClear(Integer customFieldsCacheClear) {
    this.customFieldsCacheClear = customFieldsCacheClear;
    return this;
  }

   /**
   * Get customFieldsCacheClear
   * @return customFieldsCacheClear
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getCustomFieldsCacheClear() {
    return customFieldsCacheClear;
  }

  public void setCustomFieldsCacheClear(Integer customFieldsCacheClear) {
    this.customFieldsCacheClear = customFieldsCacheClear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetStateResponse getStateResponse = (GetStateResponse) o;
    return Objects.equals(this.systemCacheClear, getStateResponse.systemCacheClear) &&
        Objects.equals(this.systemExit, getStateResponse.systemExit) &&
        Objects.equals(this.systemAlert, getStateResponse.systemAlert) &&
        Objects.equals(this.systemAccountStateChanged, getStateResponse.systemAccountStateChanged) &&
        Objects.equals(this.messageDeleted, getStateResponse.messageDeleted) &&
        Objects.equals(this.messageIncoming, getStateResponse.messageIncoming) &&
        Objects.equals(this.messageIncomingDeleted, getStateResponse.messageIncomingDeleted) &&
        Objects.equals(this.messageStateChanged, getStateResponse.messageStateChanged) &&
        Objects.equals(this.messageBulkEnd, getStateResponse.messageBulkEnd) &&
        Objects.equals(this.messageWipeEnd, getStateResponse.messageWipeEnd) &&
        Objects.equals(this.messageSent, getStateResponse.messageSent) &&
        Objects.equals(this.messageSessionDeleted, getStateResponse.messageSessionDeleted) &&
        Objects.equals(this.messageCacheClear, getStateResponse.messageCacheClear) &&
        Objects.equals(this.messageIncomingCacheClear, getStateResponse.messageIncomingCacheClear) &&
        Objects.equals(this.messageScheduleAdded, getStateResponse.messageScheduleAdded) &&
        Objects.equals(this.messageScheduleStateChanged, getStateResponse.messageScheduleStateChanged) &&
        Objects.equals(this.messageScheduleDeleted, getStateResponse.messageScheduleDeleted) &&
        Objects.equals(this.messageScheduleCacheClear, getStateResponse.messageScheduleCacheClear) &&
        Objects.equals(this.messageTemplateCacheClear, getStateResponse.messageTemplateCacheClear) &&
        Objects.equals(this.callFinished, getStateResponse.callFinished) &&
        Objects.equals(this.chatCreated, getStateResponse.chatCreated) &&
        Objects.equals(this.chatMarkedAsRead, getStateResponse.chatMarkedAsRead) &&
        Objects.equals(this.chatMuted, getStateResponse.chatMuted) &&
        Objects.equals(this.chatUnmuted, getStateResponse.chatUnmuted) &&
        Objects.equals(this.chatPinned, getStateResponse.chatPinned) &&
        Objects.equals(this.chatUnpinned, getStateResponse.chatUnpinned) &&
        Objects.equals(this.chatDeleted, getStateResponse.chatDeleted) &&
        Objects.equals(this.chatClosed, getStateResponse.chatClosed) &&
        Objects.equals(this.chatReopened, getStateResponse.chatReopened) &&
        Objects.equals(this.chatCacheClear, getStateResponse.chatCacheClear) &&
        Objects.equals(this.contactAdded, getStateResponse.contactAdded) &&
        Objects.equals(this.contactDeleted, getStateResponse.contactDeleted) &&
        Objects.equals(this.contactStateChanged, getStateResponse.contactStateChanged) &&
        Objects.equals(this.listAdded, getStateResponse.listAdded) &&
        Objects.equals(this.listDeleted, getStateResponse.listDeleted) &&
        Objects.equals(this.listStateChanged, getStateResponse.listStateChanged) &&
        Objects.equals(this.contactWipeEnd, getStateResponse.contactWipeEnd) &&
        Objects.equals(this.contactImportEnd, getStateResponse.contactImportEnd) &&
        Objects.equals(this.contactCacheClear, getStateResponse.contactCacheClear) &&
        Objects.equals(this.listCacheClear, getStateResponse.listCacheClear) &&
        Objects.equals(this.customFieldsCacheClear, getStateResponse.customFieldsCacheClear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemCacheClear, systemExit, systemAlert, systemAccountStateChanged, messageDeleted, messageIncoming, messageIncomingDeleted, messageStateChanged, messageBulkEnd, messageWipeEnd, messageSent, messageSessionDeleted, messageCacheClear, messageIncomingCacheClear, messageScheduleAdded, messageScheduleStateChanged, messageScheduleDeleted, messageScheduleCacheClear, messageTemplateCacheClear, callFinished, chatCreated, chatMarkedAsRead, chatMuted, chatUnmuted, chatPinned, chatUnpinned, chatDeleted, chatClosed, chatReopened, chatCacheClear, contactAdded, contactDeleted, contactStateChanged, listAdded, listDeleted, listStateChanged, contactWipeEnd, contactImportEnd, contactCacheClear, listCacheClear, customFieldsCacheClear);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStateResponse {\n");
    
    sb.append("    systemCacheClear: ").append(toIndentedString(systemCacheClear)).append("\n");
    sb.append("    systemExit: ").append(toIndentedString(systemExit)).append("\n");
    sb.append("    systemAlert: ").append(toIndentedString(systemAlert)).append("\n");
    sb.append("    systemAccountStateChanged: ").append(toIndentedString(systemAccountStateChanged)).append("\n");
    sb.append("    messageDeleted: ").append(toIndentedString(messageDeleted)).append("\n");
    sb.append("    messageIncoming: ").append(toIndentedString(messageIncoming)).append("\n");
    sb.append("    messageIncomingDeleted: ").append(toIndentedString(messageIncomingDeleted)).append("\n");
    sb.append("    messageStateChanged: ").append(toIndentedString(messageStateChanged)).append("\n");
    sb.append("    messageBulkEnd: ").append(toIndentedString(messageBulkEnd)).append("\n");
    sb.append("    messageWipeEnd: ").append(toIndentedString(messageWipeEnd)).append("\n");
    sb.append("    messageSent: ").append(toIndentedString(messageSent)).append("\n");
    sb.append("    messageSessionDeleted: ").append(toIndentedString(messageSessionDeleted)).append("\n");
    sb.append("    messageCacheClear: ").append(toIndentedString(messageCacheClear)).append("\n");
    sb.append("    messageIncomingCacheClear: ").append(toIndentedString(messageIncomingCacheClear)).append("\n");
    sb.append("    messageScheduleAdded: ").append(toIndentedString(messageScheduleAdded)).append("\n");
    sb.append("    messageScheduleStateChanged: ").append(toIndentedString(messageScheduleStateChanged)).append("\n");
    sb.append("    messageScheduleDeleted: ").append(toIndentedString(messageScheduleDeleted)).append("\n");
    sb.append("    messageScheduleCacheClear: ").append(toIndentedString(messageScheduleCacheClear)).append("\n");
    sb.append("    messageTemplateCacheClear: ").append(toIndentedString(messageTemplateCacheClear)).append("\n");
    sb.append("    callFinished: ").append(toIndentedString(callFinished)).append("\n");
    sb.append("    chatCreated: ").append(toIndentedString(chatCreated)).append("\n");
    sb.append("    chatMarkedAsRead: ").append(toIndentedString(chatMarkedAsRead)).append("\n");
    sb.append("    chatMuted: ").append(toIndentedString(chatMuted)).append("\n");
    sb.append("    chatUnmuted: ").append(toIndentedString(chatUnmuted)).append("\n");
    sb.append("    chatPinned: ").append(toIndentedString(chatPinned)).append("\n");
    sb.append("    chatUnpinned: ").append(toIndentedString(chatUnpinned)).append("\n");
    sb.append("    chatDeleted: ").append(toIndentedString(chatDeleted)).append("\n");
    sb.append("    chatClosed: ").append(toIndentedString(chatClosed)).append("\n");
    sb.append("    chatReopened: ").append(toIndentedString(chatReopened)).append("\n");
    sb.append("    chatCacheClear: ").append(toIndentedString(chatCacheClear)).append("\n");
    sb.append("    contactAdded: ").append(toIndentedString(contactAdded)).append("\n");
    sb.append("    contactDeleted: ").append(toIndentedString(contactDeleted)).append("\n");
    sb.append("    contactStateChanged: ").append(toIndentedString(contactStateChanged)).append("\n");
    sb.append("    listAdded: ").append(toIndentedString(listAdded)).append("\n");
    sb.append("    listDeleted: ").append(toIndentedString(listDeleted)).append("\n");
    sb.append("    listStateChanged: ").append(toIndentedString(listStateChanged)).append("\n");
    sb.append("    contactWipeEnd: ").append(toIndentedString(contactWipeEnd)).append("\n");
    sb.append("    contactImportEnd: ").append(toIndentedString(contactImportEnd)).append("\n");
    sb.append("    contactCacheClear: ").append(toIndentedString(contactCacheClear)).append("\n");
    sb.append("    listCacheClear: ").append(toIndentedString(listCacheClear)).append("\n");
    sb.append("    customFieldsCacheClear: ").append(toIndentedString(customFieldsCacheClear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

