/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "RequestNewSubaccountTokenInputObject.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

RequestNewSubaccountTokenInputObject::RequestNewSubaccountTokenInputObject()
{
    m_UserId = 0;
    m_UserIdIsSet = false;
    m_Password = utility::conversions::to_string_t("");
    m_PasswordIsSet = false;
    m_AppName = utility::conversions::to_string_t("");
    m_AppNameIsSet = false;
}

RequestNewSubaccountTokenInputObject::~RequestNewSubaccountTokenInputObject()
{
}

void RequestNewSubaccountTokenInputObject::validate()
{
    // TODO: implement validation
}

web::json::value RequestNewSubaccountTokenInputObject::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_UserIdIsSet)
    {
        val[utility::conversions::to_string_t("userId")] = ModelBase::toJson(m_UserId);
    }
    if(m_PasswordIsSet)
    {
        val[utility::conversions::to_string_t("password")] = ModelBase::toJson(m_Password);
    }
    if(m_AppNameIsSet)
    {
        val[utility::conversions::to_string_t("appName")] = ModelBase::toJson(m_AppName);
    }

    return val;
}

void RequestNewSubaccountTokenInputObject::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("userId")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("userId")];
        if(!fieldValue.is_null())
        {
            setUserId(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("password")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("password")];
        if(!fieldValue.is_null())
        {
            setPassword(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("appName")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("appName")];
        if(!fieldValue.is_null())
        {
            setAppName(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void RequestNewSubaccountTokenInputObject::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("userId"), m_UserId));
    }
    if(m_PasswordIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("password"), m_Password));
        
    }
    if(m_AppNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("appName"), m_AppName));
        
    }
}

void RequestNewSubaccountTokenInputObject::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("userId")))
    {
        setUserId(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("userId"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("password")))
    {
        setPassword(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("password"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("appName")))
    {
        setAppName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("appName"))));
    }
}

int32_t RequestNewSubaccountTokenInputObject::getUserId() const
{
    return m_UserId;
}


void RequestNewSubaccountTokenInputObject::setUserId(int32_t value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}
bool RequestNewSubaccountTokenInputObject::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void RequestNewSubaccountTokenInputObject::unsetUserId()
{
    m_UserIdIsSet = false;
}

utility::string_t RequestNewSubaccountTokenInputObject::getPassword() const
{
    return m_Password;
}


void RequestNewSubaccountTokenInputObject::setPassword(utility::string_t value)
{
    m_Password = value;
    m_PasswordIsSet = true;
}
bool RequestNewSubaccountTokenInputObject::passwordIsSet() const
{
    return m_PasswordIsSet;
}

void RequestNewSubaccountTokenInputObject::unsetPassword()
{
    m_PasswordIsSet = false;
}

utility::string_t RequestNewSubaccountTokenInputObject::getAppName() const
{
    return m_AppName;
}


void RequestNewSubaccountTokenInputObject::setAppName(utility::string_t value)
{
    m_AppName = value;
    m_AppNameIsSet = true;
}
bool RequestNewSubaccountTokenInputObject::appNameIsSet() const
{
    return m_AppNameIsSet;
}

void RequestNewSubaccountTokenInputObject::unsetAppName()
{
    m_AppNameIsSet = false;
}

}
}
}
}

