/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * RequestSenderIdInputObject.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_RequestSenderIdInputObject_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_RequestSenderIdInputObject_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  RequestSenderIdInputObject
    : public ModelBase
{
public:
    RequestSenderIdInputObject();
    virtual ~RequestSenderIdInputObject();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// RequestSenderIdInputObject members

    /// <summary>
    /// The Sender ID that you are applying for. *   11 characters maximum; *   Only Latin based characters and digits are allowed; *   Should contain at least 1 letter. 
    /// </summary>
    utility::string_t getSenderId() const;
    bool senderIdIsSet() const;
    void unsetSenderId();
    void setSenderId(utility::string_t value);
    /// <summary>
    /// Explanation of why you need this Sender ID.
    /// </summary>
    utility::string_t getExplanation() const;
    bool explanationIsSet() const;
    void unsetExplanation();
    void setExplanation(utility::string_t value);

protected:
    utility::string_t m_SenderId;
    bool m_SenderIdIsSet;
    utility::string_t m_Explanation;
    bool m_ExplanationIsSet;
};

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_RequestSenderIdInputObject_H_ */
