/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UpdateSurveyCountryItem.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_UpdateSurveyCountryItem_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_UpdateSurveyCountryItem_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  UpdateSurveyCountryItem
    : public ModelBase
{
public:
    UpdateSurveyCountryItem();
    virtual ~UpdateSurveyCountryItem();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UpdateSurveyCountryItem members

    /// <summary>
    /// The 2-letter ISO country code.
    /// </summary>
    utility::string_t getCountry() const;
        void setCountry(utility::string_t value);
    /// <summary>
    /// User inbound phone ID.
    /// </summary>
    int32_t getUserInboundId() const;
        void setUserInboundId(int32_t value);

protected:
    utility::string_t m_Country;
        int32_t m_UserInboundId;
    };

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_UpdateSurveyCountryItem_H_ */
