/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UserCustomField.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_UserCustomField_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_UserCustomField_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  UserCustomField
    : public ModelBase
{
public:
    UserCustomField();
    virtual ~UserCustomField();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UserCustomField members

    /// <summary>
    /// Custom field ID.
    /// </summary>
    int32_t getId() const;
        void setId(int32_t value);
    /// <summary>
    /// Custom field name.
    /// </summary>
    utility::string_t getName() const;
        void setName(utility::string_t value);
    /// <summary>
    /// Custom field creation time.
    /// </summary>
    utility::datetime getCreatedAt() const;
        void setCreatedAt(utility::datetime value);

protected:
    int32_t m_Id;
        utility::string_t m_Name;
        utility::datetime m_CreatedAt;
    };

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_UserCustomField_H_ */
