/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextmagicClient);
  }
}(this, function(expect, TextmagicClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetBalanceNotificationSettingsResponse', function() {
      beforeEach(function() {
        instance = new TextmagicClient.GetBalanceNotificationSettingsResponse();
      });

      it('should create an instance of GetBalanceNotificationSettingsResponse', function() {
        // TODO: update the code to test GetBalanceNotificationSettingsResponse
        expect(instance).to.be.a(TextmagicClient.GetBalanceNotificationSettingsResponse);
      });

      it('should have the property lowBalanceNotification (base name: "lowBalanceNotification")', function() {
        // TODO: update the code to test the property lowBalanceNotification
        expect(instance).to.have.property('lowBalanceNotification');
        // expect(instance.lowBalanceNotification).to.be(expectedValueLiteral);
      });

      it('should have the property alertBalance (base name: "alertBalance")', function() {
        // TODO: update the code to test the property alertBalance
        expect(instance).to.have.property('alertBalance');
        // expect(instance.alertBalance).to.be(expectedValueLiteral);
      });

      it('should have the property alertPhone (base name: "alertPhone")', function() {
        // TODO: update the code to test the property alertPhone
        expect(instance).to.have.property('alertPhone');
        // expect(instance.alertPhone).to.be(expectedValueLiteral);
      });

      it('should have the property alertEmail1 (base name: "alertEmail1")', function() {
        // TODO: update the code to test the property alertEmail1
        expect(instance).to.have.property('alertEmail1');
        // expect(instance.alertEmail1).to.be(expectedValueLiteral);
      });

      it('should have the property alertEmail2 (base name: "alertEmail2")', function() {
        // TODO: update the code to test the property alertEmail2
        expect(instance).to.have.property('alertEmail2');
        // expect(instance.alertEmail2).to.be(expectedValueLiteral);
      });

      it('should have the property alertEmail3 (base name: "alertEmail3")', function() {
        // TODO: update the code to test the property alertEmail3
        expect(instance).to.have.property('alertEmail3');
        // expect(instance.alertEmail3).to.be(expectedValueLiteral);
      });

    });
  });

}));
