/*
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextmagicClient);
  }
}(this, function(expect, TextmagicClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetSubaccountsWithTokensInputObject', function() {
      beforeEach(function() {
        instance = new TextmagicClient.GetSubaccountsWithTokensInputObject();
      });

      it('should create an instance of GetSubaccountsWithTokensInputObject', function() {
        // TODO: update the code to test GetSubaccountsWithTokensInputObject
        expect(instance).to.be.a(TextmagicClient.GetSubaccountsWithTokensInputObject);
      });

      it('should have the property appName (base name: "appName")', function() {
        // TODO: update the code to test the property appName
        expect(instance).to.have.property('appName');
        // expect(instance.appName).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

    });
  });

}));
